apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opomlytravel-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: OpomlyTravel.infres.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: opomlytravel-service
            port:
              number: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: opomlytravel-service
  labels:
    run: opomlytravel
spec:
  selector:
    app: opomlytravel
  ports:
  - protocol: TCP
    port: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opomlytravel
  labels:
    app: opomlytravel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: opomlytravel
  template:
    metadata:
      labels:
        app: opomlytravel
    spec:
      containers:
      - name: opomlytravel
        image: registry.infres.fr/OpomlyTravel
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api-docs
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api-docs
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5 